// Breeder cats data from original website
import { getBreederImages, getParentImage } from "@/utils/image-utils";

export const BREEDER_CATS_DATA = [
  {
    id: 1,
    name: "Bengalivo Stumblin'In (aka Lilo)",
    color: "black spotted tabby",
    sex: "girl (proven)",
    dob: "8 july 2024",
    father: "LA SGC Bengalivo Million Reasons",
    mother: "SilverCrown Supernatural",
    coi: "24.186",
    generation: "9G",
    genetics: "PKdef carrier (N/K), PRA-b N/N by parentage & not tested for colour (could be melanistic carrier)",
    pedigree: "Stamboom van Bengalivo",
    images: getBreederImages("Bengalivo Stumblin'In (aka Lilo)", 12),
    fatherImageUrl: getParentImage("LA SGC Bengalivo Million Reasons (aka Eos)"),
    motherImageUrl: getParentImage("SilverCrown")
  },
  {
    id: 2,
    name: "MioDollarBaby Maya (aka Maya)",
    color: "black spotted tabby",
    sex: "girl (proven)",
    dob: "16 june 2021",
    father: "MioDollarBaby Atta",
    mother: "MioDollarBaby Gaja",
    coi: "24.995",
    generation: "9G",
    genetics: "PKdef N/N by parentage, N/PRA-b, no snow carrier",
    pedigree: "Pedigree",
    images: getBreederImages("MioDollarBaby Maya (aka Maya)", 7),
    fatherImageUrl: getParentImage("MioDollarBaby Atta"),
    motherImageUrl: getParentImage("MioDollarBaby Gaja")
  },
  {
    id: 3,
    name: "IW SGC Bengalivo Another One Bites Dust (aka Dust)",
    color: "black spotted tabby",
    sex: "neutered boy (now showing in alter class for his LA)",
    dob: "25 july 2023",
    father: "LA SGC Bengalivo Million Reasons",
    mother: "MioDollarBaby Maya",
    coi: "24.481",
    generation: "9G",
    genetics: "PKdef N/K, N/PRA-b, sepia carrier (C/cb)",
    pedigree: "Pedigree",
    images: getBreederImages("IW SGC Bengalivo Another One Bites Dust (aka Dust)", 11),
    fatherImageUrl: getParentImage("LA SGC Bengalivo Million Reasons (aka Eos)"),
    motherImageUrl: getParentImage("MioDollarBaby Maya")
  },
  {
    id: 4,
    name: "LA SGC Bengalivo Million Reasons (aka Eos)",
    color: "black spotted tabby",
    sex: "boy (neutered)",
    dob: "11 february 2021",
    father: "RW SGC Pixel des Griffes de Feu",
    mother: "Queshua des Griffes de Feu",
    coi: "27.676",
    generation: "8G",
    genetics: "PKdef N/K, PRA-b N/N by parentage, sepia carrier (C/cb)",
    pedigree: "Pedigree",
    images: getBreederImages("LA SGC Bengalivo Million Reasons (aka Eos)", 12),
    fatherImageUrl: getParentImage("RW SGC Pixel des Griffes de Feu"),
    motherImageUrl: getParentImage("Queshua des Griffes de Feu")
  },
  {
    id: 5,
    name: "Hypnotic'bengal Unstoppable (aka Copper)",
    color: "seal sepia spotted tabby",
    sex: "boy (proven)",
    dob: "2 october 2023",
    father: "Hypnotic'bengal Raoni",
    mother: "Wild Paradise Tigrinha",
    coi: "",
    generation: "8G",
    genetics: "PKdef N/N and PRA-b N/N by parentage, sepia (cb/cb)",
    pedigree: "Pedigree",
    images: getBreederImages("Hypnotic'bengal Unstoppable (aka Copper)", 8),
    fatherImageUrl: getParentImage("Hypnotic'bengal Raoni"),
    motherImageUrl: getParentImage("Wild Paradise Tigrinha")
  },
  {
    id: 6,
    name: "Bengalivo Armed With Love (aka Blue)",
    color: "black spotted tabby",
    sex: "girl (proven)",
    dob: "19 may 2022",
    father: "LA SGC Bengalivo Million Reasons",
    mother: "MioDollarBaby Maya",
    coi: "24.481",
    generation: "9G",
    genetics: "PKdef N/N, N/PRA-b, no carrier of snow",
    pedigree: "Pedigree",
    images: getBreederImages("Bengalivo Armed With Love (aka Blue)", 3),
    fatherImageUrl: getParentImage("LA SGC Bengalivo Million Reasons (aka Eos)"),
    motherImageUrl: getParentImage("MioDollarBaby Maya")
  },
  {
    id: 7,
    name: "Bengalivo Just Give Me A Reason (aka Pink)",
    color: "black spotted tabby",
    sex: "girl (proven)",
    dob: "22 november 2022",
    father: "LA SGC Bengalivo Million Reasons",
    mother: "SilverCrown Supernatural",
    coi: "24.186",
    generation: "9G",
    genetics: "PKdef and PRA-b N/N, melanistic carrier & no snow carrier",
    pedigree: "Pedigree",
    images: getBreederImages("Bengalivo Just Give Me A Reason (aka Pink)", 5),
    fatherImageUrl: getParentImage("LA SGC Bengalivo Million Reasons (aka Eos)"),
    motherImageUrl: getParentImage("SilverCrown")
  },
  {
    id: 8,
    name: "Goralguru Noblesse",
    color: "black spotted tabby",
    sex: "girl (upcoming)",
    dob: "23 october 2024",
    father: "IW SGC Goralguru CoupDe Coeur",
    mother: "DGC Guru Luna Nera",
    coi: "25.005",
    generation: "6G",
    genetics: "PKdef N/N by parentage & PRA-b (test pending)",
    pedigree: "Pedigree",
    images: getBreederImages("Goralguru Noblesse", 1),
    fatherImageUrl: getParentImage("IW SGC Goralguru CoupDe Coeur"),
    motherImageUrl: getParentImage("DGC Guru Luna Nera")
  },
  {
    id: 9,
    name: "Bengalivo Cry Baby (aka Moana)",
    color: "black spotted tabby",
    sex: "girl (proven)",
    dob: "19 july 2024",
    father: "SGC Minileo Gandalf",
    mother: "Bengalivo Jump For Joy",
    coi: "",
    generation: "7G",
    genetics: "PKdef N/N, PRA-b N/N by parentage & seal lynx (C/cs) carrier",
    pedigree: "Pedigree",
    images: getBreederImages("Bengalivo Cry Baby (aka Moana)", 5),
    fatherImageUrl: getParentImage("SGC Minileo Gandalf"),
    motherImageUrl: getParentImage("Bengalivo Jump For Joy")
  },
  {
    id: 10,
    name: "Bengalivo Femme Fatale (aka Ivory)",
    color: "seal sepia spotted tabby",
    sex: "girl (upcoming)",
    dob: "20 may 2023",
    father: "SGC Minileo Gandalf",
    mother: "Bengalivo Jump For Joy",
    coi: "",
    generation: "7G",
    genetics: "PKdef N/K, PRA-b N/N by parentage & sepia (cb/cb)",
    pedigree: "Pedigree",
    images: getBreederImages("Bengalivo Femme Fatale (aka Ivory)", 6),
    fatherImageUrl: getParentImage("SGC Minileo Gandalf"),
    motherImageUrl: getParentImage("Bengalivo Jump For Joy")
  },
  {
    id: 11,
    name: "RW SGC Batifoleurs Zawadi",
    color: "black spotted tabby",
    sex: "boy (upcoming)",
    dob: "3 july 2024",
    father: "RW SGC Batifoleurs Anando",
    mother: "RW TGC Cooperdolls Bella Rose",
    coi: "29.064",
    generation: "9G",
    genetics: "PKdef N/K and PRA-b N/N by parentage & sepia carrier (C/cb)",
    pedigree: "Pedigree",
    images: getBreederImages("RW SGC Batifoleurs Zawadi", 8),
    fatherImageUrl: getParentImage("RW SGC Batifoleurs Anando"),
    motherImageUrl: getParentImage("RW TGC Cooperdolls Bella Rose")
  }
];

